BEGIN;
DROP TRIGGER IF EXISTS filing_work_artifact_drift_guard ON source_artifacts;
DROP TABLE IF EXISTS filing_work_attempts;
DROP TABLE IF EXISTS filing_work_items;
DROP FUNCTION IF EXISTS enforce_filing_work_acceptance();
DROP FUNCTION IF EXISTS set_filing_work_item_clock();
DROP FUNCTION IF EXISTS enforce_filing_work_item_transition();
DROP FUNCTION IF EXISTS enforce_filing_work_attempt_insert();
DROP FUNCTION IF EXISTS enforce_filing_work_attempt_update();
DROP FUNCTION IF EXISTS prevent_filing_work_attempt_delete();
DROP FUNCTION IF EXISTS prevent_filing_artifact_drift();
DROP FUNCTION IF EXISTS enforce_filing_work_attempt_completion();
DELETE FROM schema_migrations WHERE version = '007_filing_work_ledger';
COMMIT;
