"""Backtest tab for historical technical signal validation."""

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

_CONFIG = {"displayModeBar": False}


def _fmt_pct(value) -> str:
    return "N/A" if value is None or pd.isna(value) else f"{value:.2f}%"


def _fmt_money(value) -> str:
    return "N/A" if value is None or pd.isna(value) else f"Rp {value:,.0f}"


def render_backtest_tab(backtest: dict, ticker: str) -> None:
    st.markdown(
        f"<h3 style='font-size:1rem;font-weight:600;color:#F5F5F7;margin-bottom:16px;'>{ticker} — Backtest Validation</h3>",
        unsafe_allow_html=True,
    )
    if not backtest or backtest.get("error"):
        st.warning(backtest.get("error", "Backtest data is unavailable."))
        return

    summary = backtest.get("summary", {})
    if backtest.get("research_only"):
        st.warning("Gross research result only — broker costs are not configured and this evidence cannot pass the action gate.")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Trades", f"{summary.get('total_trades', 0)}")
    c2.metric("Win Rate", _fmt_pct(summary.get("win_rate")))
    c3.metric("Avg Return", _fmt_pct(summary.get("average_return")))
    pf = summary.get("profit_factor")
    pf_text = "∞" if pf == float("inf") else (f"{pf:.2f}" if pf is not None else "N/A")
    c4.metric("Profit Factor", pf_text)

    c5, c6, c7, c8 = st.columns(4)
    c5.metric("Expectancy", _fmt_money(summary.get("expectancy")))
    c6.metric("Max Drawdown", _fmt_pct(summary.get("max_drawdown")))
    c7.metric("TP Hit Rate", _fmt_pct(summary.get("tp_hit_rate")))
    c8.metric("SL Hit Rate", _fmt_pct(summary.get("sl_hit_rate")))

    confidence = backtest.get("setup_confidence")
    if confidence is not None:
        st.info(f"Historical setup confidence: {confidence:.0f}%")
    else:
        st.info("Validated evidence needs at least five market years and 30 completed trades.")

    equity_curve = backtest.get("equity_curve")
    if equity_curve is not None and not equity_curve.empty:
        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=equity_curve.index,
                y=equity_curve["Equity"],
                name="Equity",
                line=dict(color="#30D158", width=1.6),
            )
        )
        fig.update_layout(
            height=340,
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(family="Inter, -apple-system, sans-serif", color="#F5F5F7", size=12),
            margin=dict(l=10, r=10, t=20, b=10),
            yaxis=dict(gridcolor="#2C2C2E", zeroline=False, tickfont=dict(color="#8E8E93", size=11)),
            xaxis=dict(showgrid=False, zeroline=False, tickfont=dict(color="#8E8E93", size=11)),
        )
        st.plotly_chart(fig, use_container_width=True, config=_CONFIG)

    signal_stats = backtest.get("signal_stats", {})
    with st.expander("Signal Stats"):
        rows = [
            {"Metric": "Evaluated Bars", "Value": signal_stats.get("evaluated_bars", "N/A")},
            {"Metric": "Buy Signals", "Value": signal_stats.get("buy_signals", "N/A")},
            {
                "Metric": "Buy Signal Rate",
                "Value": _fmt_pct(signal_stats.get("buy_signal_rate")),
            },
            {"Metric": "Max Holding Days", "Value": signal_stats.get("max_holding_days", "N/A")},
        ]
        st.dataframe(rows, use_container_width=True, hide_index=True)

    trades = backtest.get("trades")
    if trades is not None and not trades.empty:
        display = trades.copy()
        for col in ["Entry Date", "Exit Date"]:
            display[col] = pd.to_datetime(display[col]).dt.strftime("%Y-%m-%d")
        st.markdown(
            "<h3 style='font-size:1rem;font-weight:600;color:#F5F5F7;margin-bottom:8px;'>Completed Trades</h3>",
            unsafe_allow_html=True,
        )
        st.dataframe(display.sort_values("Exit Date", ascending=False), use_container_width=True, hide_index=True)
    else:
        st.info("No completed trades were generated by the current rules.")
